### ISSUE TITLE
Unecessary complex code

### ISSUE THREAD

**Issue by joostf** [TimoVerkroost/minor-web-app-from-scratch#4]
Try to simplify this code, there is no need to cache the oldHash value

https://github.com/TimoVerkroost/minor-web-app-from-scratch/blob/9bc8c36b8c68ceb1fdd9ab81e69a127dfe7c013c/opdracht-5-spa/assets/js/app.js#L14

**Comment by TimoVerkroost** [comment]
Thanks I think i fixed it. The code is much shorter.
